SELECT A.JOB, A.DEPTNO, ROUND(AVG(A.SAL),2) AS AVG_SAL
  FROM EMP A 
  --GROUP BY ROLLUP(JOB, DEPTNO)
  --GROUP BY ROLLUP((JOB,DEPTNO))
  --GROUP BY ROLLUP((JOB),(DEPTNO))
  GROUP BY JOB, ROLLUP(DEPTNO)
  ORDER BY 1,2
  ;